"use client";

import Link from "next/link";
import { useState } from "react";
import PageHeader from "@/app/components/PageHeader";
import { contests, type ContestStatus } from "@/mock/data";

const filters: Array<"All" | ContestStatus> = ["All", "Registration Open", "Active", "Upcoming", "Finished"];
const colors: Record<ContestStatus, string> = { Active: "text-green-400 bg-green-400/10 border-green-400/20", "Registration Open": "text-kjprimary bg-kjprimary/10 border-kjprimary/20", Upcoming: "text-blue-400 bg-blue-400/10 border-blue-400/20", Finished: "text-kjtext-muted bg-kjbg border-kjborder" };

export default function ContestsPage() {
  const [filter, setFilter] = useState<"All" | ContestStatus>("All");
  const [registered, setRegistered] = useState<string[]>(contests.filter((contest) => contest.registered).map((contest) => contest.id));
  const visible = contests.filter((contest) => filter === "All" || contest.status === filter);
  return <><PageHeader eyebrow="Arena / schedules" title="Contest Arena" description="Register for upcoming events, enter active arenas, and inspect final results from completed contests." /><main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"><div className="flex flex-wrap gap-2 mb-7">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`px-4 py-2 rounded border text-xs font-mono ${filter === item ? "border-kjprimary/50 bg-kjprimary/10 text-kjprimary" : "border-kjborder text-kjtext-muted"}`}>{item}</button>)}</div><div className="grid md:grid-cols-2 gap-4">{visible.map((contest) => <article key={contest.id} className="bg-kjsurface border border-kjborder rounded-lg p-5 hover:border-kjborder-bright"><div className="flex justify-between gap-4 mb-3"><Link href={`/contests/${contest.id}`} className="font-mono font-semibold text-kjtext hover:text-kjprimary">{contest.title}</Link><span className={`shrink-0 rounded-full border px-2 py-1 text-[11px] font-mono ${colors[contest.status]}`}>{contest.status}</span></div><p className="text-sm text-kjtext-muted leading-6 mb-5">{contest.description}</p><div className="grid grid-cols-2 gap-y-2 text-xs font-mono text-kjtext-muted mb-5"><span>START <b className="text-kjtext font-normal">{contest.start}</b></span><span>END <b className="text-kjtext font-normal">{contest.end}</b></span><span>PROBLEMS <b className="text-kjtext font-normal">{contest.problems}</b></span><span>PARTICIPANTS <b className="text-kjtext font-normal">{contest.participants}</b></span></div><div className="flex gap-3"><Link href={`/contests/${contest.id}`} className="bg-kjprimary text-kjbg font-mono font-bold text-xs px-4 py-2 rounded">{contest.status === "Active" ? "ENTER ARENA" : contest.status === "Finished" ? "VIEW RESULTS" : "VIEW DETAILS"}</Link>{(contest.status === "Registration Open" || contest.status === "Upcoming") && <button onClick={() => setRegistered((current) => current.includes(contest.id) ? current.filter((id) => id !== contest.id) : [...current, contest.id])} className="border border-kjborder text-kjtext font-mono text-xs px-4 py-2 rounded hover:border-kjprimary hover:text-kjprimary">{registered.includes(contest.id) ? "REGISTERED" : "REGISTER"}</button>}</div></article>)}</div></main></>;
}
