"use client";

import { useState } from "react";
import PageHeader from "@/app/components/PageHeader";
import { contests, leaderboard } from "@/mock/data";

export default function RankingsPage() {
  const [contest, setContest] = useState(contests[0].id);
  return <><PageHeader eyebrow="Standings / live mock" title="Leaderboard" description="Contest rankings sorted by problems solved descending, then penalty ascending. The live indicator demonstrates the realtime UI state without a WebSocket." /><main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"><div className="flex flex-wrap justify-between gap-4 mb-6"><select value={contest} onChange={(event) => setContest(event.target.value)} className="bg-kjsurface border border-kjborder rounded px-4 py-3 text-sm font-mono text-kjtext">{contests.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><span className="border border-kjprimary/20 bg-kjprimary/5 text-kjprimary rounded px-4 py-3 text-xs font-mono">● LIVE · updated just now</span></div><div className="border border-kjborder rounded-lg overflow-x-auto"><table className="w-full min-w-[720px]"><thead><tr className="bg-kjsurface">{["Rank", "Username", "A", "B", "C", "D", "Solved", "Penalty"].map((heading) => <th key={heading} className="px-5 py-4 text-left text-[11px] uppercase tracking-widest font-mono text-kjtext-muted">{heading}</th>)}</tr></thead><tbody>{leaderboard.map((row) => <tr key={row.username} className={`border-t border-kjborder/70 ${row.username === "Shiv" ? "bg-kjprimary/5" : ""}`}><td className="px-5 py-4 font-mono text-kjprimary">{String(row.rank).padStart(2, "0")}</td><td className="px-5 py-4 font-mono text-kjtext">{row.username}{row.username === "Shiv" && <span className="ml-2 text-[10px] text-kjprimary">YOU</span>}</td>{row.solved.map((status, index) => <td key={`${row.username}-${index}`} className={`px-5 py-4 font-mono text-sm ${status === "AC" ? "text-green-400" : status === "WA" ? "text-red-400" : "text-kjtext-muted"}`}>{status}</td>)}<td className="px-5 py-4 font-mono text-kjtext">{row.solvedCount}</td><td className="px-5 py-4 font-mono text-kjtext-muted">{row.penalty} min</td></tr>)}</tbody></table></div><p className="mt-4 text-xs font-mono text-kjtext-muted">Penalty = first accepted time + 20 minutes for each incorrect submission before first AC.</p></main></>;
}
